version: 3
services:
    tracker-server:
      image: beaock/nginx-fastdfs
      #volumes:
      #  - $PWD/docker/fastdfs-tracker:/etc/fdfs/
      network_mode: "host"
      container_name: tracker-server
      command: "./tracker.sh"
    storage-server:
      image: beaock/nginx-fastdfs
      volumes:
        - $PWD/docker/storage_base_path:/data/fast_data
        -  $PWD/docker/store_path0:/fastdfs/store_path
      ports:
        - 8088:80
        - 23000:23000
      environment:
        TRACKER_SERVER: "tracker-server:22122"
        GROUP_NAME: "M00"
      network_mode: "host"
      command: "./storage.sh"
      depends_on:
        - tracker-server