docker run -p 6379:6379 --name redis -v $PWD/data:/data  -d redis:3.2 redis-server --appendonly yes --requirepass 123456

version: '3'
services:
  redis:
    image: redis:3.2
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - $PWD/data:/data
    command:
      redis-server --appendonly yes --requirepass 123456