version: '3.1'
services:
  gitlab:
    image: jeremygilbert/gitlab-ce-zh
    container_name: "gitlab"
    restart: unless-stopped
    privileged: true
    hostname: '39.100.252.231'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://39.100.252.231'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
    ports:
      - '80:80'
      - '443:443'
      - '1022:22'
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/data:/var/opt/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
  gitlab-runner:
    image: jeremygilbert/gitlab-runner
    restart: always
    container_name: gitlab-runner
    depends_on:
      - gitlab
    privileged: true
    volumes:
      - ./config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.m2/repository:/home/gitlab-runner/.m2/repository
      - /root/.m2/repository:/root/.m2/repository