version: '3.1'
services:
  gitlab:
    image: jeremygilbert/gitlab-ce-zh
    container_name: "gitlab"
    restart: unless-stopped
    privileged: true
    hostname: 'localhost'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
    ports:
      - '80:80'
      - '443:443'
      - '1022:22'
  gitlab-runner:
    image: jeremygilbert/gitlab-runner
    restart: always
    container_name: gitlab-runner
    depends_on:
      - gitlab
    privileged: true
   